import { proto, MessageGenerationOptions, WASocket } from 'baileys';
import { Action } from './action.js';
import { Buffer } from 'buffer';
import Long from 'long';
export interface SerializedMessage {
    raw: proto.IWebMessageInfo;
    message: proto.IWebMessageInfo['message'];
    key: proto.IMessageKey;
    from: string;
    fromMe: boolean;
    id: string;
    device: string;
    isBaileys: boolean;
    isGroup: boolean;
    participant: string | null;
    sender: string;
    pushName: string;
    type: string | undefined;
    msg: any;
    mentions: string[];
    body: string | null;
    prefix: string | null;
    prefixes: string[];
    command: string | null;
    args: string[];
    text: string;
    argsParsed: Record<string, string | boolean>;
    expiration: number;
    timestamp: number;
    isMedia: boolean;
    mimetype: string | undefined | null;
    size: number | Long | undefined | null;
    height: number | undefined | null;
    width: number | undefined | null;
    isAnimated: boolean | undefined | null;
    reply: (text: string, options?: MessageGenerationOptions) => Promise<proto.IWebMessageInfo | undefined>;
    download: () => Promise<Buffer>;
    react: (emoji: string) => Promise<proto.IWebMessageInfo | undefined>;
    isQuoted: boolean;
    quoted: SerializedMessage | null;
}
export declare function serialize(client: WASocket & Action, msg: proto.IWebMessageInfo): Promise<SerializedMessage | undefined>;
